"""create table

Revision ID: 105d36966c1d
Revises: 
Create Date: 2025-06-25 20:55:26.497630

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '105d36966c1d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Etudiant',
    sa.Column('id_etudiant', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(length=255), nullable=False),
    sa.Column('prenom', sa.String(length=255), nullable=False),
    sa.Column('Email', sa.String(length=255), nullable=False),
    sa.Column('date_naissance', sa.Date(), nullable=True),
    sa.Column('telephone', sa.String(length=100), nullable=True),
    sa.Column('class', sa.String(length=20), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('Photo', sa.String(length=255), nullable=True),
    sa.Column('annee_universitaire', sa.String(length=100), nullable=True),
    sa.Column('genre', sa.String(length=255), nullable=True),
    sa.Column('date_inscription', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id_etudiant')
    )
    op.create_table('Importation',
    sa.Column('id_import', sa.Integer(), nullable=False),
    sa.Column('nom_fichier', sa.String(length=255), nullable=True),
    sa.Column('type_import', sa.String(length=50), nullable=True),
    sa.Column('taille_fichier', sa.BigInteger(), nullable=True),
    sa.Column('nombre_lignes', sa.Integer(), nullable=True),
    sa.Column('nombre_traitees', sa.Integer(), nullable=True),
    sa.Column('lignes_erreur', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('rapport_erreurs', sa.Text(), nullable=True),
    sa.Column('date_import', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id_import')
    )
    op.create_table('Professeur',
    sa.Column('id_prof', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(length=50), nullable=False),
    sa.Column('prenom', sa.String(length=50), nullable=False),
    sa.Column('Email', sa.String(length=255), nullable=False),
    sa.Column('date_naissance', sa.Date(), nullable=True),
    sa.Column('Telephone', sa.String(length=100), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('Photo', sa.String(length=255), nullable=True),
    sa.Column('genre', sa.String(length=255), nullable=True),
    sa.Column('Departement', sa.String(length=255), nullable=True),
    sa.Column('Specialité', sa.String(length=255), nullable=True),
    sa.Column('siteWeb', sa.String(length=255), nullable=True),
    sa.Column('annee_universitaire', sa.String(length=100), nullable=True),
    sa.Column('Date_embauche', sa.Date(), nullable=True),
    sa.Column('LinkedIn', sa.String(length=255), nullable=True),
    sa.Column('Biographie', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id_prof')
    )
    op.create_table('User',
    sa.Column('id_user', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=250), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id_user')
    )
    op.create_table('Matiere',
    sa.Column('id_matiere', sa.Integer(), nullable=False),
    sa.Column('nom_matiere', sa.String(length=255), nullable=False),
    sa.Column('coefficient', sa.Float(), nullable=True),
    sa.Column('volume_horaire', sa.Integer(), nullable=True),
    sa.Column('semestre', sa.String(length=25), nullable=True),
    sa.Column('classe', sa.String(length=25), nullable=True),
    sa.Column('annee_universitaire', sa.String(length=100), nullable=True),
    sa.Column('id_prof', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_prof'], ['Professeur.id_prof'], ),
    sa.PrimaryKeyConstraint('id_matiere')
    )
    op.create_table('Note',
    sa.Column('id_note', sa.Integer(), nullable=False),
    sa.Column('etudiant_id', sa.Integer(), nullable=True),
    sa.Column('matiere_id', sa.Integer(), nullable=True),
    sa.Column('note', sa.Float(), nullable=True),
    sa.Column('coefficient', sa.Float(), nullable=True),
    sa.Column('semester', sa.String(length=50), nullable=True),
    sa.Column('academic_year', sa.String(length=50), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['etudiant_id'], ['Etudiant.id_etudiant'], ),
    sa.ForeignKeyConstraint(['matiere_id'], ['Matiere.id_matiere'], ),
    sa.PrimaryKeyConstraint('id_note')
    )
    op.create_table('Bulletin',
    sa.Column('id_bulletin', sa.Integer(), nullable=False),
    sa.Column('etudiant_id', sa.Integer(), nullable=True),
    sa.Column('note_id', sa.Integer(), nullable=True),
    sa.Column('moyenne', sa.Float(), nullable=True),
    sa.Column('Etat', sa.String(length=50), nullable=True),
    sa.Column('mention', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['etudiant_id'], ['Etudiant.id_etudiant'], ),
    sa.ForeignKeyConstraint(['note_id'], ['Note.id_note'], ),
    sa.PrimaryKeyConstraint('id_bulletin')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Bulletin')
    op.drop_table('Note')
    op.drop_table('Matiere')
    op.drop_table('User')
    op.drop_table('Professeur')
    op.drop_table('Importation')
    op.drop_table('Etudiant')
    # ### end Alembic commands ###
